<?php 
/*
Copyright alexonbstudio
Listed manual by Alexon Balaangue 
to Json Array to 2h50 works time done
Phone Region Code
Please do not edit this files for 
using the libs/libphonenumber-for-php/*
*/
# exemple $PhoneRegionCodeManualNumbers['$lang']['COUNTRY-CODE']
$PhoneRegionCodeManualNumbers = array(
 'render-list' => array(
   'COUNTRY' => 'COUNTRY', /*country/
   'COUNTRY-CODE' => 'COUNTRY CODE', /*alpha 2*/
   'ISO-CODES' => 'ISO CODES' /*alpha 3*/
 ),
 'af' => array(
   'COUNTRY' => 'Afghanistan',
   'COUNTRY-CODE' => 'AF',
   'ISO-CODES' => 'AFG'
 ),
 'al' => array(
   'COUNTRY' => 'Albania',
   'COUNTRY-CODE' => 'AL',
   'ISO-CODES' => 'ALB'
 ),
 'dz' => array(
   'COUNTRY' => 'Algeria',
   'COUNTRY-CODE' => 'DZ',
   'ISO-CODES' => 'DZA'
 ),
 'as' => array(
   'COUNTRY' => 'American Samoa',
   'COUNTRY-CODE' => 'AS',
   'ISO-CODES' => 'ASM'
 ),
 'ad' => array(
   'COUNTRY' => 'Andorra',
   'COUNTRY-CODE' => 'AD',
   'ISO-CODES' => 'AND'
 ),
 'ao' => array(
   'COUNTRY' => 'Angola',
   'COUNTRY-CODE' => 'AO',
   'ISO-CODES' => 'AGO'
 ),
 'ai' => array(
   'COUNTRY' => 'Anguilla',
   'COUNTRY-CODE' => 'AI',
   'ISO-CODES' => 'AIA'
 ),
 'aq' => array(
   'COUNTRY' => 'Antarctica',
   'COUNTRY-CODE' => 'AQ',
   'ISO-CODES' => 'ATA'
 ),
 'ag' => array(
   'COUNTRY' => 'Antigua and Barbuda',
   'COUNTRY-CODE' => 'AG',
   'ISO-CODES' => 'ATG'
 ),
 'ar' => array(
   'COUNTRY' => 'Argentina',
   'COUNTRY-CODE' => 'AR',
   'ISO-CODES' => 'ARG'
 ),
 'am' => array(
   'COUNTRY' => 'Armenia',
   'COUNTRY-CODE' => 'AM',
   'ISO-CODES' => 'ARM'
 ),
 'aw' => array(
   'COUNTRY' => 'Aruba',
   'COUNTRY-CODE' => 'AW',
   'ISO-CODES' => 'ABW'
 ),
 'au' => array(
   'COUNTRY' => 'Australia',
   'COUNTRY-CODE' => 'AU',
   'ISO-CODES' => 'AUS'
 ),
 'at' => array(
   'COUNTRY' => 'Austria',
   'COUNTRY-CODE' => 'AT',
   'ISO-CODES' => 'AUT'
 ),
 'az' => array(
   'COUNTRY' => 'Azerbaijan',
   'COUNTRY-CODE' => 'AZ',
   'ISO-CODES' => 'AZE'
 ),
 'bs' => array(
   'COUNTRY' => 'Bahamas',
   'COUNTRY-CODE' => 'BS',
   'ISO-CODES' => 'BHS'
 ),
 'bh' => array(
   'COUNTRY' => 'Bahrain',
   'COUNTRY-CODE' => 'BH',
   'ISO-CODES' => 'BHR'
 ),
 'bd' => array(
   'COUNTRY' => 'Bangladesh',
   'COUNTRY-CODE' => 'BD',
   'ISO-CODES' => 'BGD'
 ),
 'bb' => array(
   'COUNTRY' => 'Barbados',
   'COUNTRY-CODE' => 'BB',
   'ISO-CODES' => 'BRB'
 ),
 'by' => array(
   'COUNTRY' => 'Belarus',
   'COUNTRY-CODE' => 'BY',
   'ISO-CODES' => 'BLR'
 ),
 'be' => array(
   'COUNTRY' => 'Belgium',
   'COUNTRY-CODE' => 'BE',
   'ISO-CODES' => 'BEL'
 ),
 'bz' => array(
   'COUNTRY' => 'Belize',
   'COUNTRY-CODE' => 'BZ',
   'ISO-CODES' => 'BLZ'
 ),
 'bj' => array(
   'COUNTRY' => 'Benin',
   'COUNTRY-CODE' => 'BJ',
   'ISO-CODES' => 'BEN'
 ),
 'bm' => array(
   'COUNTRY' => 'Bermuda',
   'COUNTRY-CODE' => 'BM',
   'ISO-CODES' => 'BMU'
 ),
 'bt' => array(
   'COUNTRY' => 'Bhutan',
   'COUNTRY-CODE' => 'BT',
   'ISO-CODES' => 'BTN'
 ),
 'bo' => array(
   'COUNTRY' => 'Bolivia',
   'COUNTRY-CODE' => 'BO',
   'ISO-CODES' => 'BOL'
 ),
 'ba' => array(
   'COUNTRY' => 'Bosnia and Herzegovina',
   'COUNTRY-CODE' => 'BA',
   'ISO-CODES' => 'BIH'
 ),
 'bw' => array(
   'COUNTRY' => 'Botswana',
   'COUNTRY-CODE' => 'BW',
   'ISO-CODES' => 'BWA'
 ),
 'br' => array(
   'COUNTRY' => 'Brazil',
   'COUNTRY-CODE' => 'BR',
   'ISO-CODES' => 'BRA'
 ),
 'io' => array(
   'COUNTRY' => 'British Indian Ocean Territory',
   'COUNTRY-CODE' => 'IO',
   'ISO-CODES' => 'IOT'
 ),
 'vg' => array(
   'COUNTRY' => 'British Virgin Islands',
   'COUNTRY-CODE' => 'VG',
   'ISO-CODES' => 'VGB'
 ),
 'bn' => array(
   'COUNTRY' => 'Brunei',
   'COUNTRY-CODE' => 'BN',
   'ISO-CODES' => 'BRN'
 ),
 'bg' => array(
   'COUNTRY' => 'Bulgaria',
   'COUNTRY-CODE' => 'BG',
   'ISO-CODES' => 'BGR'
 ),
 'bf' => array(
   'COUNTRY' => 'Burkina Faso',
   'COUNTRY-CODE' => 'BF',
   'ISO-CODES' => 'BFA'
 ),
 'bi' => array(
   'COUNTRY' => 'Burundi',
   'COUNTRY-CODE' => 'BI',
   'ISO-CODES' => 'BDI'
 ),
 'kh' => array(
   'COUNTRY' => 'Cambodia',
   'COUNTRY-CODE' => 'KH',
   'ISO-CODES' => 'KHM'
 ),
 'cm' => array(
   'COUNTRY' => 'Cameroon',
   'COUNTRY-CODE' => 'CM',
   'ISO-CODES' => 'CMR'
 ),
 'ca' => array(
   'COUNTRY' => 'Canada',
   'COUNTRY-CODE' => 'CA',
   'ISO-CODES' => 'CAN'
 ),
 'cv' => array(
   'COUNTRY' => 'Cape Verde',
   'COUNTRY-CODE' => 'CV',
   'ISO-CODES' => 'CPV'
 ),
 'ky' => array(
   'COUNTRY' => 'Cayman Islands',
   'COUNTRY-CODE' => 'KY',
   'ISO-CODES' => 'CYM'
 ),
 'cf' => array(
   'COUNTRY' => 'Central African Republic',
   'COUNTRY-CODE' => 'CF',
   'ISO-CODES' => 'CAF'
 ),
 'td' => array(
   'COUNTRY' => 'Chad',
   'COUNTRY-CODE' => 'TD',
   'ISO-CODES' => 'TCD'
 ),
 'cl' => array(
   'COUNTRY' => 'Chile',
   'COUNTRY-CODE' => 'CL',
   'ISO-CODES' => 'CHL'
 ),
 'cn' => array(
   'COUNTRY' => 'China',
   'COUNTRY-CODE' => 'CN',
   'ISO-CODES' => 'CHN'
 ),
 'cx' => array(
   'COUNTRY' => 'Christmas Island',
   'COUNTRY-CODE' => 'CX',
   'ISO-CODES' => 'CXR'
 ),
 'cc' => array(
   'COUNTRY' => 'Cocos Islands',
   'COUNTRY-CODE' => 'CC',
   'ISO-CODES' => 'CCK'
 ),
 'co' => array(
   'COUNTRY' => 'Colombia',
   'COUNTRY-CODE' => 'CO',
   'ISO-CODES' => 'COL'
 ),
 'km' => array(
   'COUNTRY' => 'Comoros',
   'COUNTRY-CODE' => 'KM',
   'ISO-CODES' => 'COM'
 ),
 'ck' => array(
   'COUNTRY' => 'Cook Islands',
   'COUNTRY-CODE' => 'CK',
   'ISO-CODES' => 'COK'
 ),
 'cr' => array(
   'COUNTRY' => 'Costa Rica',
   'COUNTRY-CODE' => 'CR',
   'ISO-CODES' => 'CRI'
 ),
 'hr' => array(
   'COUNTRY' => 'Croatia',
   'COUNTRY-CODE' => 'HR',
   'ISO-CODES' => 'HRV'
 ),
 'cu' => array(
   'COUNTRY' => 'Cuba',
   'COUNTRY-CODE' => 'CU',
   'ISO-CODES' => 'CUB'
 ),
 'cw' => array(
   'COUNTRY' => 'Curacao',
   'COUNTRY-CODE' => 'CW',
   'ISO-CODES' => 'CUW'
 ),
 'cy' => array(
   'COUNTRY' => 'Cyprus',
   'COUNTRY-CODE' => 'CY',
   'ISO-CODES' => 'CYP'
 ),
 'cz' => array(
   'COUNTRY' => 'Czech Republic',
   'COUNTRY-CODE' => 'CZ',
   'ISO-CODES' => 'CZE'
 ),
 'cd' => array(
   'COUNTRY' => 'Democratic Republic of the Congo',
   'COUNTRY-CODE' => 'CD',
   'ISO-CODES' => 'COD'
 ),
 'dk' => array(
   'COUNTRY' => 'Denmark',
   'COUNTRY-CODE' => 'DK',
   'ISO-CODES' => 'DNK'
 ),
 'dj' => array(
   'COUNTRY' => 'Djibouti',
   'COUNTRY-CODE' => 'DJ',
   'ISO-CODES' => 'DJI'
 ),
 'dm' => array(
   'COUNTRY' => 'Dominica',
   'COUNTRY-CODE' => 'DM',
   'ISO-CODES' => 'DMA'
 ),
 'do' => array(
   'COUNTRY' => 'Dominican Republic',
   'COUNTRY-CODE' => 'DO',
   'ISO-CODES' => 'DOM'
 ),
 'tl' => array(
   'COUNTRY' => 'East Timor',
   'COUNTRY-CODE' => 'TL',
   'ISO-CODES' => 'TLS'
 ),
 'ec' => array(
   'COUNTRY' => 'Ecuador',
   'COUNTRY-CODE' => 'EC',
   'ISO-CODES' => 'ECU'
 ),
 'eg' => array(
   'COUNTRY' => 'Egypt',
   'COUNTRY-CODE' => 'EG',
   'ISO-CODES' => 'EGY'
 ),
 'sv' => array(
   'COUNTRY' => 'El Salvador',
   'COUNTRY-CODE' => 'SV',
   'ISO-CODES' => 'SLV'
 ),
 'gq' => array(
   'COUNTRY' => 'Equatorial Guinea',
   'COUNTRY-CODE' => 'GQ',
   'ISO-CODES' => 'GNQ'
 ),
 'er' => array(
   'COUNTRY' => 'Eritrea',
   'COUNTRY-CODE' => 'ER',
   'ISO-CODES' => 'ERI'
 ),
 'ee' => array(
   'COUNTRY' => 'Estonia',
   'COUNTRY-CODE' => 'EE',
   'ISO-CODES' => 'EST'
 ),
 'et' => array(
   'COUNTRY' => 'Ethiopia',
   'COUNTRY-CODE' => 'ET',
   'ISO-CODES' => 'ETH'
 ),
 'fk' => array(
   'COUNTRY' => 'Falkland Islands',
   'COUNTRY-CODE' => 'FK',
   'ISO-CODES' => 'FLK'
 ),
 'po' => array(
   'COUNTRY' => 'Faroe Islands',
   'COUNTRY-CODE' => 'FO',
   'ISO-CODES' => 'FRO'
 ),
 'pj' => array(
   'COUNTRY' => 'Fiji',
   'COUNTRY-CODE' => 'FJ',
   'ISO-CODES' => 'FJI'
 ),
 'fi' => array(
   'COUNTRY' => 'Finland',
   'COUNTRY-CODE' => 'FI',
   'ISO-CODES' => 'FIN'
 ),
 'fr' => array(
   'COUNTRY' => 'France',
   'COUNTRY-CODE' => 'FR',
   'ISO-CODES' => 'FRA'
 ),
 'pf' => array(
   'COUNTRY' => 'French Polynesia',
   'COUNTRY-CODE' => 'PF',
   'ISO-CODES' => 'PYF'
 ),
 'ga' => array(
   'COUNTRY' => 'Gabon',
   'COUNTRY-CODE' => 'GA',
   'ISO-CODES' => 'GAB'
 ),
 'gm' => array(
   'COUNTRY' => 'Gambia',
   'COUNTRY-CODE' => 'GM',
   'ISO-CODES' => 'GMB'
 ),
 'ge' => array(
   'COUNTRY' => 'Georgia',
   'COUNTRY-CODE' => 'GE',
   'ISO-CODES' => 'GEO'
 ),
 'de' => array(
   'COUNTRY' => 'Germany',
   'COUNTRY-CODE' => 'DE',
   'ISO-CODES' => 'DEU'
 ),
 'gh' => array(
   'COUNTRY' => 'Ghana',
   'COUNTRY-CODE' => 'GH',
   'ISO-CODES' => 'GHA'
 ),
 'gt' => array(
   'COUNTRY' => 'Gibraltar',
   'COUNTRY-CODE' => 'GI',
   'ISO-CODES' => 'GIB'
 ),
 'gr' => array(
   'COUNTRY' => 'Greece',
   'COUNTRY-CODE' => 'GR',
   'ISO-CODES' => 'GRC'
 ),
 'gl' => array(
   'COUNTRY' => 'Greenland',
   'COUNTRY-CODE' => 'GL',
   'ISO-CODES' => 'GRL'
 ),
 'gd' => array(
   'COUNTRY' => 'Grenada',
   'COUNTRY-CODE' => 'GD',
   'ISO-CODES' => 'GRD'
 ),
 'gu' => array(
   'COUNTRY' => 'Guam',
   'COUNTRY-CODE' => 'GU',
   'ISO-CODES' => 'GUM'
 ),
 'gt' => array(
   'COUNTRY' => 'Guatemala',
   'COUNTRY-CODE' => 'GT',
   'ISO-CODES' => 'GTM'
 ),
 'gg' => array(
   'COUNTRY' => 'Guernsey',
   'COUNTRY-CODE' => 'GG',
   'ISO-CODES' => 'GGY'
 ),
 'gn' => array(
   'COUNTRY' => 'Guinea',
   'COUNTRY-CODE' => 'GN',
   'ISO-CODES' => 'GIN'
 ),
 'gw' => array(
   'COUNTRY' => 'Guinea-Bissau',
   'COUNTRY-CODE' => 'GW',
   'ISO-CODES' => 'GNB'
 ),
 'gy' => array(
   'COUNTRY' => 'Guyana',
   'COUNTRY-CODE' => 'GY',
   'ISO-CODES' => 'GUY'
 ),
 'ht' => array(
   'COUNTRY' => 'Haiti',
   'COUNTRY-CODE' => 'HT',
   'ISO-CODES' => 'HTI'
 ),
 'hn' => array(
   'COUNTRY' => 'Honduras',
   'COUNTRY-CODE' => 'HN',
   'ISO-CODES' => 'HND'
 ),
 'hk' => array(
   'COUNTRY' => 'Hong Kong',
   'COUNTRY-CODE' => 'HK',
   'ISO-CODES' => 'HKG'
 ),
 'hu' => array(
   'COUNTRY' => 'Hungary',
   'COUNTRY-CODE' => 'HU',
   'ISO-CODES' => 'HUN'
 ),
 'is' => array(
   'COUNTRY' => 'Iceland',
   'COUNTRY-CODE' => 'IS',
   'ISO-CODES' => 'ISL'
 ),
 'in' => array(
   'COUNTRY' => 'India',
   'COUNTRY-CODE' => 'IN',
   'ISO-CODES' => 'IND'
 ),
 'id' => array(
   'COUNTRY' => 'Indonesia',
   'COUNTRY-CODE' => 'ID',
   'ISO-CODES' => 'IDN'
 ),
 'ir' => array(
   'COUNTRY' => 'Iran',
   'COUNTRY-CODE' => 'IR',
   'ISO-CODES' => 'IRN'
 ),
 'iq' => array(
   'COUNTRY' => 'Iraq',
   'COUNTRY-CODE' => 'IQ',
   'ISO-CODES' => 'IRQ'
 ),
 'ie' => array(
   'COUNTRY' => 'Ireland',
   'COUNTRY-CODE' => 'IE',
   'ISO-CODES' => 'IRL'
 ),
 'im' => array(
   'COUNTRY' => 'Isle of Man',
   'COUNTRY-CODE' => 'IM',
   'ISO-CODES' => 'IMN'
 ),
 'il' => array(
   'COUNTRY' => 'Israel',
   'COUNTRY-CODE' => 'IL',
   'ISO-CODES' => 'ISR'
 ),
 'it' => array(
   'COUNTRY' => 'Italy',
   'COUNTRY-CODE' => 'IT',
   'ISO-CODES' => 'ITA'
 ),
 'ci' => array(
   'COUNTRY' => 'Ivory Coast',
   'COUNTRY-CODE' => 'CI',
   'ISO-CODES' => 'CIV'
 ),
 'jm' => array(
   'COUNTRY' => 'Jamaica',
   'COUNTRY-CODE' => 'JM',
   'ISO-CODES' => 'JAM'
 ),
 'jp' => array(
   'COUNTRY' => 'Japan',
   'COUNTRY-CODE' => 'JP',
   'ISO-CODES' => 'JPN'
 ),
 'je' => array(
   'COUNTRY' => 'Jersey',
   'COUNTRY-CODE' => 'JE',
   'ISO-CODES' => 'JEY'
 ),
 'jo' => array(
   'COUNTRY' => 'Jordan',
   'COUNTRY-CODE' => 'JO',
   'ISO-CODES' => 'JOR'
 ),
 'kz' => array(
   'COUNTRY' => 'Kazakhstan',
   'COUNTRY-CODE' => 'KZ',
   'ISO-CODES' => 'KAZ'
 ),
 'ke' => array(
   'COUNTRY' => 'Kenya',
   'COUNTRY-CODE' => 'KE',
   'ISO-CODES' => 'KEN'
 ),
 'ki' => array(
   'COUNTRY' => 'Kiribati',
   'COUNTRY-CODE' => 'KI',
   'ISO-CODES' => 'KIR'
 ),
 'xk' => array(
   'COUNTRY' => 'Kosovo',
   'COUNTRY-CODE' => 'XK',
   'ISO-CODES' => 'XKX'
 ),
 'kw' => array(
   'COUNTRY' => 'Kuwait',
   'COUNTRY-CODE' => 'KW',
   'ISO-CODES' => 'KWT'
 ),
 'kg' => array(
   'COUNTRY' => 'Kyrgyzstan',
   'COUNTRY-CODE' => 'KG',
   'ISO-CODES' => 'KGZ'
 ),
 'la' => array(
   'COUNTRY' => 'Laos',
   'COUNTRY-CODE' => 'LA',
   'ISO-CODES' => 'LAO'
 ),
 'lv' => array(
   'COUNTRY' => 'Latvia',
   'COUNTRY-CODE' => 'LV',
   'ISO-CODES' => 'LVA'
 ),
 'lb' => array(
   'COUNTRY' => 'Lebanon',
   'COUNTRY-CODE' => 'LB',
   'ISO-CODES' => 'LBN'
 ),
 'ls' => array(
   'COUNTRY' => 'Lesotho',
   'COUNTRY-CODE' => 'LS',
   'ISO-CODES' => 'LSO'
 ),
 'lr' => array(
   'COUNTRY' => 'Liberia',
   'COUNTRY-CODE' => 'LR',
   'ISO-CODES' => 'LBR'
 ),
 'ly' => array(
   'COUNTRY' => 'Libya',
   'COUNTRY-CODE' => 'LY',
   'ISO-CODES' => 'LBY'
 ),
 'li' => array(
   'COUNTRY' => 'Liechtenstein',
   'COUNTRY-CODE' => 'LI',
   'ISO-CODES' => 'LIE'
 ),
 'lt' => array(
   'COUNTRY' => 'Lithuania',
   'COUNTRY-CODE' => 'LT',
   'ISO-CODES' => 'LTU'
 ),
 'lu' => array(
   'COUNTRY' => 'Luxembourg',
   'COUNTRY-CODE' => 'LU',
   'ISO-CODES' => 'LUX'
 ),
 'mo' => array(
   'COUNTRY' => 'Macau',
   'COUNTRY-CODE' => 'MO',
   'ISO-CODES' => 'MAC'
 ),
 'mk' => array(
   'COUNTRY' => 'Macedonia',
   'COUNTRY-CODE' => 'MK',
   'ISO-CODES' => 'MKD'
 ),
 'mg' => array(
   'COUNTRY' => 'Madagascar',
   'COUNTRY-CODE' => 'MG',
   'ISO-CODES' => 'MDG'
 ),
 'mw' => array(
   'COUNTRY' => 'Malawi',
   'COUNTRY-CODE' => 'MW',
   'ISO-CODES' => 'MWI'
 ),
 'my' => array(
   'COUNTRY' => 'Malaysia',
   'COUNTRY-CODE' => 'MY',
   'ISO-CODES' => 'MYS'
 ),
 'mv' => array(
   'COUNTRY' => 'Maldives',
   'COUNTRY-CODE' => 'MV',
   'ISO-CODES' => 'MDV'
 ),
 'ml' => array(
   'COUNTRY' => 'Mali',
   'COUNTRY-CODE' => 'ML',
   'ISO-CODES' => 'MLI'
 ),
 'mt' => array(
   'COUNTRY' => 'Malta',
   'COUNTRY-CODE' => 'MT',
   'ISO-CODES' => 'MLT'
 ),
 'mh' => array(
   'COUNTRY' => 'Marshall Islands',
   'COUNTRY-CODE' => 'MH',
   'ISO-CODES' => 'MHL'
 ),
 'mr' => array(
   'COUNTRY' => 'Mauritania',
   'COUNTRY-CODE' => 'MR',
   'ISO-CODES' => 'MRT'
 ),
 'mu' => array(
   'COUNTRY' => 'Mauritius',
   'COUNTRY-CODE' => 'MU',
   'ISO-CODES' => 'MUS'
 ),
 'yt' => array(
   'COUNTRY' => 'Mayotte',
   'COUNTRY-CODE' => 'YT',
   'ISO-CODES' => 'MYT'
 ),
 'mx' => array(
   'COUNTRY' => 'Mexico',
   'COUNTRY-CODE' => 'MX',
   'ISO-CODES' => 'MEX'
 ),
 'fm' => array(
   'COUNTRY' => 'Micronesia',
   'COUNTRY-CODE' => 'FM',
   'ISO-CODES' => 'FSM'
 ),
 'md' => array(
   'COUNTRY' => 'Moldova',
   'COUNTRY-CODE' => 'MD',
   'ISO-CODES' => 'MDA'
 ),
 'mc' => array(
   'COUNTRY' => 'Monaco',
   'COUNTRY-CODE' => 'MC',
   'ISO-CODES' => 'MCO'
 ),
 'mn' => array(
   'COUNTRY' => 'Mongolia',
   'COUNTRY-CODE' => 'MN',
   'ISO-CODES' => 'MNG'
 ),
 'me' => array(
   'COUNTRY' => 'Montenegro',
   'COUNTRY-CODE' => 'ME',
   'ISO-CODES' => 'MNE'
 ),
 'ms' => array(
   'COUNTRY' => 'Montserrat',
   'COUNTRY-CODE' => 'MS',
   'ISO-CODES' => 'MSR'
 ),
 'ma' => array(
   'COUNTRY' => 'Morocco',
   'COUNTRY-CODE' => 'MA',
   'ISO-CODES' => 'MAR'
 ),
 'mz' => array(
   'COUNTRY' => 'Mozambique',
   'COUNTRY-CODE' => 'MZ',
   'ISO-CODES' => 'MOZ'
 ),
 'mm' => array(
   'COUNTRY' => 'Myanmar',
   'COUNTRY-CODE' => 'MM',
   'ISO-CODES' => 'MMR'
 ),
 'na' => array(
   'COUNTRY' => 'Namibia',
   'COUNTRY-CODE' => 'NA',
   'ISO-CODES' => 'NAM'
 ),
 'nr' => array(
   'COUNTRY' => 'Nauru',
   'COUNTRY-CODE' => 'NR',
   'ISO-CODES' => 'NRU'
 ),
 'np' => array(
   'COUNTRY' => 'Nepal',
   'COUNTRY-CODE' => 'NP',
   'ISO-CODES' => 'NPL'
 ),
 'nl' => array(
   'COUNTRY' => 'Netherlands',
   'COUNTRY-CODE' => 'NL',
   'ISO-CODES' => 'NLD'
 ),
 'an' => array(
   'COUNTRY' => 'Netherlands Antilles',
   'COUNTRY-CODE' => 'AN',
   'ISO-CODES' => 'ANT'
 ),
 'nc' => array(
   'COUNTRY' => 'New Caledonia',
   'COUNTRY-CODE' => 'NC',
   'ISO-CODES' => 'NCL'
 ),
 'nz' => array(
   'COUNTRY' => 'New Zealand',
   'COUNTRY-CODE' => 'NZ',
   'ISO-CODES' => 'NZL'
 ),
 'ni' => array(
   'COUNTRY' => 'Nicaragua',
   'COUNTRY-CODE' => 'NI',
   'ISO-CODES' => 'NIC'
 ),
 'ne' => array(
   'COUNTRY' => 'Niger',
   'COUNTRY-CODE' => 'NE',
   'ISO-CODES' => 'NER'
 ),
 'ng' => array(
   'COUNTRY' => 'Nigeria',
   'COUNTRY-CODE' => 'NG',
   'ISO-CODES' => 'NGA'
 ),
 'nu' => array(
   'COUNTRY' => 'Niue',
   'COUNTRY-CODE' => 'NU',
   'ISO-CODES' => 'NIU'
 ),
 'kp' => array(
   'COUNTRY' => 'North Korea',
   'COUNTRY-CODE' => 'KP',
   'ISO-CODES' => 'PRK'
 ),
 'mp' => array(
   'COUNTRY' => 'Northern Mariana Islands',
   'COUNTRY-CODE' => 'MP',
   'ISO-CODES' => 'MNP'
 ),
 'no' => array(
   'COUNTRY' => 'Norway',
   'COUNTRY-CODE' => 'NO',
   'ISO-CODES' => 'NOR'
 ),
 'om' => array(
   'COUNTRY' => 'Oman',
   'COUNTRY-CODE' => 'OM',
   'ISO-CODES' => 'OMN'
 ),
 'pk' => array(
   'COUNTRY' => 'Pakistan',
   'COUNTRY-CODE' => 'PK',
   'ISO-CODES' => 'PAK'
 ),
 'pw' => array(
   'COUNTRY' => 'Palau',
   'COUNTRY-CODE' => 'PW',
   'ISO-CODES' => 'PLW'
 ),
 'ps' => array(
   'COUNTRY' => 'Palestine',
   'COUNTRY-CODE' => 'PS',
   'ISO-CODES' => 'PSE'
 ),
 'pa' => array(
   'COUNTRY' => 'Panama',
   'COUNTRY-CODE' => 'PA',
   'ISO-CODES' => 'PAN'
 ),
 'pg' => array(
   'COUNTRY' => 'Papua New Guinea',
   'COUNTRY-CODE' => 'PG',
   'ISO-CODES' => 'PNG'
 ),
 'py' => array(
   'COUNTRY' => 'Paraguay',
   'COUNTRY-CODE' => 'PY',
   'ISO-CODES' => 'PRY'
 ),
 'pe' => array(
   'COUNTRY' => 'Peru',
   'COUNTRY-CODE' => 'PE',
   'ISO-CODES' => 'PER'
 ),
 'ph' => array(
   'COUNTRY' => 'Philippines',
   'COUNTRY-CODE' => 'PH',
   'ISO-CODES' => 'PHL'
 ),
 'pn' => array(
   'COUNTRY' => 'Pitcairn',
   'COUNTRY-CODE' => 'PN',
   'ISO-CODES' => 'PCN'
 ),
 'pl' => array(
   'COUNTRY' => 'Poland',
   'COUNTRY-CODE' => 'PL',
   'ISO-CODES' => 'POL'
 ),
 'pt' => array(
   'COUNTRY' => 'Portugal',
   'COUNTRY-CODE' => 'PT',
   'ISO-CODES': 'PRT'
 ),
 'pr' => array(
   'COUNTRY' => 'Puerto Rico',
   'COUNTRY-CODE' => 'PR',
   'ISO-CODES' => 'PRI'
 ),
 'qa' => array(
   'COUNTRY' => 'Qatar',
   'COUNTRY-CODE' => 'QA',
   'ISO-CODES' => 'QAT'
 ),
 'cg' => array(
   'COUNTRY' => 'Republic of the Congo',
   'COUNTRY-CODE' => 'CG',
   'ISO-CODES' => 'COG'
 ),
 're' => array(
   'COUNTRY' => 'Reunion',
   'COUNTRY-CODE' => 'RE',
   'ISO-CODES' => 'REU'
 ),
 'ro' => array(
   'COUNTRY' => 'Romania',
   'COUNTRY-CODE' => 'RO',
   'ISO-CODES' => 'ROU'
 ),
 'ru' => array(
   'COUNTRY' => 'Russia',
   'COUNTRY-CODE' => 'RU',
   'ISO-CODES' => 'RUS'
 ),
 'rw' => array(
   'COUNTRY' => 'Rwanda',
   'COUNTRY-CODE' => 'RW',
   'ISO-CODES' => 'RWA'
 ),
 'bl' => array(
   'COUNTRY' => 'Saint Barthelemy',
   'COUNTRY-CODE' => 'BL',
   'ISO-CODES' => 'BLM'
 ),
 'sh' => array(
   'COUNTRY' => 'Saint Helena',
   'COUNTRY-CODE' => 'SH',
   'ISO-CODES' => 'SHN'
 ),
 'kn' => array(
   'COUNTRY' => 'Saint Kitts and Nevis',
   'COUNTRY-CODE' => 'KN',
   'ISO-CODES' => 'KNA'
 ),
 'lc' => array(
   'COUNTRY' => 'Saint Lucia',
   'COUNTRY-CODE' => 'LC',
   'ISO-CODES' => 'LCA'
 ),
 'mf' => array(
   'COUNTRY' => 'Saint Martin',
   'COUNTRY-CODE' => 'MF',
   'ISO-CODES' => 'MAF'
 ),
 'pm' => array(
   'COUNTRY' => 'Saint Pierre and Miquelon',
   'COUNTRY-CODE' => 'PM',
   'ISO-CODES' => 'SPM'
 ),
 'vc' => array(
   'COUNTRY' => 'Saint Vincent and the Grenadines',
   'COUNTRY-CODE' => 'VC',
   'ISO-CODES' => 'VCT'
 ),
 'ws' => array(
   'COUNTRY' => 'Samoa',
   'COUNTRY-CODE' => 'WS',
   'ISO-CODES' => 'WSM'
 ),
 'sm' => array(
   'COUNTRY' => 'San Marino',
   'COUNTRY-CODE' => 'SM',
   'ISO-CODES' => 'SMR'
 ),
 'st' => array(
   'COUNTRY' => 'Sao Tome and Principe',
   'COUNTRY-CODE' => 'ST',
   'ISO-CODES' => 'STP'
 ),
 'sa' => array(
   'COUNTRY' => 'Saudi Arabia',
   'COUNTRY-CODE' => 'SA',
   'ISO-CODES' => 'SAU'
 ),
 'sn' => array(
   'COUNTRY' => 'Senegal',
   'COUNTRY-CODE' => 'SN',
   'ISO-CODES' => 'SEN'
 ),
 'rs' => array(
   'COUNTRY' => 'Serbia',
   'COUNTRY-CODE' => 'RS',
   'ISO-CODES' => 'SRB'
 ),
 'sc' => array(
   'COUNTRY' => 'Seychelles',
   'COUNTRY-CODE' => 'SC',
   'ISO-CODES' => 'SYC'
 ),
 'sl' => array(
   'COUNTRY' => 'Sierra Leone',
   'COUNTRY-CODE' => 'SL',
   'ISO-CODES' => 'SLE'
 ),
 'sg' => array(
   'COUNTRY' => 'Singapore',
   'COUNTRY-CODE' => 'SG',
   'ISO-CODES' => 'SGP'
 ),
 'sx' => array(
   'COUNTRY' => 'Sint Maarten',
   'COUNTRY-CODE' => 'SX',
   'ISO-CODES' => 'SXM'
 ),
 'sk' => array(
   'COUNTRY' => 'Slovakia',
   'COUNTRY-CODE' => 'SK',
   'ISO-CODES' => 'SVK'
 ),
 'si' => array(
   'COUNTRY' => 'Slovenia',
   'COUNTRY-CODE' => 'SI',
   'ISO-CODES' => 'SVN'
 ),
 'sb' => array(
   'COUNTRY' => 'Solomon Islands',
   'COUNTRY-CODE' => 'SB',
   'ISO-CODES' => 'SLB'
 ),
 'so' => array(
   'COUNTRY' => 'Somalia',
   'COUNTRY-CODE' => 'SO',
   'ISO-CODES' => 'SOM'
 ),
 'za' => array(
   'COUNTRY' => 'South Africa',
   'COUNTRY-CODE' => 'ZA',
   'ISO-CODES' => 'ZAF'
 ),
 'kr' => array(
   'COUNTRY' => 'South Korea',
   'COUNTRY-CODE' => 'KR',
   'ISO-CODES' => 'KOR'
 ),
 'ss' => array(
   'COUNTRY' => 'South Sudan',
   'COUNTRY-CODE' => 'SS',
   'ISO-CODES' => 'SSD'
 ),
 'es' => array(
   'COUNTRY' => 'Spain',
   'COUNTRY-CODE' => 'ES',
   'ISO-CODES' => 'ESP'
 ),
 'lk' => array(
   'COUNTRY' => 'Sri Lanka',
   'COUNTRY-CODE' => 'LK',
   'ISO-CODES' => 'LKA'
 ),
 'sd' => array(
   'COUNTRY' => 'Sudan',
   'COUNTRY-CODE' => 'SD',
   'ISO-CODES' => 'SDN'
 ),
 'sr' => array(
   'COUNTRY' => 'Suriname',
   'COUNTRY-CODE' => 'SR',
   'ISO-CODES' => 'SUR'
 ),
 'sj' => array(
   'COUNTRY' => 'Svalbard and Jan Mayen',
   'COUNTRY-CODE' => 'SJ',
   'ISO-CODES' => 'SJM'
 ),
 'cz' => array(
   'COUNTRY' => 'Swaziland',
   'COUNTRY-CODE' => 'SZ',
   'ISO-CODES' => 'SWZ'
 ),
 'se' => array(
   'COUNTRY' => 'Sweden',
   'COUNTRY-CODE' => 'SE',
   'ISO-CODES' => 'SWE'
 ),
 'ch' => array(
   'COUNTRY' => 'Switzerland',
   'COUNTRY-CODE' => 'CH',
   'ISO-CODES' => 'CHE'
 ),
 'sy' => array(
   'COUNTRY' => 'Syria',
   'COUNTRY-CODE' => 'SY',
   'ISO-CODES' => 'SYR'
 ),
 'tw' => array(
   'COUNTRY' => 'Taiwan',
   'COUNTRY-CODE' => 'TW',
   'ISO-CODES' => 'TWN'
 ),
 'tj' => array(
   'COUNTRY' => 'Tajikistan',
   'COUNTRY-CODE' => 'TJ',
   'ISO-CODES' => 'TJK'
 ),
 'tz' => array(
   'COUNTRY' => 'Tanzania',
   'COUNTRY-CODE' => 'TZ',
   'ISO-CODES' => 'TZA'
 ),
 'th' => array(
   'COUNTRY' => 'Thailand',
   'COUNTRY-CODE' => 'TH',
   'ISO-CODES' => 'THA'
 ),
 'tg' => array(
   'COUNTRY' => 'Togo',
   'COUNTRY-CODE' => 'TG',
   'ISO-CODES' => 'TGO'
 ),
 'tk' => array(
   'COUNTRY' => 'Tokelau',
   'COUNTRY-CODE' => 'TK',
   'ISO-CODES' => 'TKL'
 ),
 'to' => array(
   'COUNTRY' => 'Tonga',
   'COUNTRY-CODE' => 'TO',
   'ISO-CODES' => 'TON'
 ),
 'tt' => array(
   'COUNTRY' => 'Trinidad and Tobago',
   'COUNTRY-CODE' => 'TT',
   'ISO-CODES' => 'TTO'
 ),
 'tn' => array(
   'COUNTRY' => 'Tunisia',
   'COUNTRY-CODE' => 'TN',
   'ISO-CODES' => 'TUN'
 ),
 'tr' => array(
   'COUNTRY' => 'Turkey',
   'COUNTRY-CODE' => 'TR',
   'ISO-CODES' => 'TUR'
 ),
 'tm' => array(
   'COUNTRY' => 'Turkmenistan',
   'COUNTRY-CODE' => 'TM',
   'ISO-CODES' => 'TKM'
 ),
 'tc' => array(
   'COUNTRY' => 'Turks and Caicos Islands',
   'COUNTRY-CODE' => 'TC',
   'ISO-CODES' => 'TCA'
 ),
 'tv' => array(
   'COUNTRY' => 'Tuvalu',
   'COUNTRY-CODE' => 'TV',
   'ISO-CODES' => 'TUV'
 ),
 'vi' => array(
   'COUNTRY' => 'U.S. Virgin Islands',
   'COUNTRY-CODE' => 'VI',
   'ISO-CODES' => 'VIR'
 ),
 'ug' => array(
   'COUNTRY' => 'Uganda',
   'COUNTRY-CODE' => 'UG',
   'ISO-CODES' => 'UGA'
 ),
 'ua' => array(
   'COUNTRY' => 'Ukraine',
   'COUNTRY-CODE' => 'UA',
   'ISO-CODES' => 'UKR'
 ),
 'ae' => array(
   'COUNTRY' => 'United Arab Emirates',
   'COUNTRY-CODE' => 'AE',
   'ISO-CODES' => 'ARE'
 ),
 'gb' => array(
   'COUNTRY' => 'United Kingdom',
   'COUNTRY-CODE' => 'GB',
   'ISO-CODES' => 'GBR'
 ),
 'us' => array(
   'COUNTRY' => 'United States',
   'COUNTRY-CODE' => 'US',
   'ISO-CODES' => 'USA'
 ),
 'uy' => array(
   'COUNTRY' => 'Uruguay',
   'COUNTRY-CODE' => 'UY',
   'ISO-CODES' => 'URY'
 ),
 'uz' => array(
   'COUNTRY' => 'Uzbekistan',
   'COUNTRY-CODE' => 'UZ',
   'ISO-CODES' => 'UZB'
 ),
 'vu' => array(
   'COUNTRY' => 'Vanuatu',
   'COUNTRY-CODE' => 'VU',
   'ISO-CODES' => 'VUT'
 ),
 'va' => array(
   'COUNTRY' => 'Vatican',
   'COUNTRY-CODE' => 'VA',
   'ISO-CODES' => 'VAT'
 ),
 've' => array(
   'COUNTRY' => 'Venezuela',
   'COUNTRY-CODE' => 'VE',
   'ISO-CODES' => 'VEN'
 ),
 'vn' => array(
   'COUNTRY' => 'Vietnam',
   'COUNTRY-CODE' => 'VN',
   'ISO-CODES' => 'VNM'
 ),
 'wf' => array(
   'COUNTRY' => 'Wallis and Futuna',
   'COUNTRY-CODE' => 'WF',
   'ISO-CODES' => 'WLF'
 ),
 'eh' => array(
   'COUNTRY' => 'Western Sahara',
   'COUNTRY-CODE' => 'EH',
   'ISO-CODES' => 'ESH'
 ),
 'ye' => array(
   'COUNTRY' => 'Yemen',
   'COUNTRY-CODE' => 'YE',
   'ISO-CODES' => 'YEM'
 ),
 'zm' => array(
   'COUNTRY' => 'Zambia',
   'COUNTRY-CODE' => 'ZM',
   'ISO-CODES' => 'ZMB'
 ),
 'zw' => array(
   'COUNTRY' => 'Zimbabwe',
   'COUNTRY-CODE' => 'ZW',
   'ISO-CODES' => 'ZWE'
 ),
 'af' => array(
   'COUNTRY' => 'Afghanistan',
   'COUNTRY-CODE' => 'AF',
   'ISO-CODES' => 'AFG'
 ),
 'al' => array(
   'COUNTRY' => 'Albania',
   'COUNTRY-CODE' => 'AL',
   'ISO-CODES' => 'ALB'
 ),
 'dz' => array(
   'COUNTRY' => 'Algeria',
   'COUNTRY-CODE' => 'DZ',
   'ISO-CODES' => 'DZA'
 ),
 'as' => array(
   'COUNTRY' => 'American Samoa',
   'COUNTRY-CODE' => 'AS',
   'ISO-CODES' => 'ASM'
 ),
 'ad' => array(
   'COUNTRY' => 'Andorra',
   'COUNTRY-CODE' => 'AD',
   'ISO-CODES' => 'AND'
 ),
 'ao' => array(
   'COUNTRY' => 'Angola',
   'COUNTRY-CODE' => 'AO',
   'ISO-CODES' => 'AGO'
 ),
 'ai' => array(
   'COUNTRY' => 'Anguilla',
   'COUNTRY-CODE' => 'AI',
   'ISO-CODES' => 'AIA'
 ),
 'aq' => array(
   'COUNTRY' => 'Antarctica',
   'COUNTRY-CODE' => 'AQ',
   'ISO-CODES' => 'ATA'
 ),
 'ag' => array(
   'COUNTRY' => 'Antigua and Barbuda',
   'COUNTRY-CODE' => 'AG',
   'ISO-CODES' => 'ATG'
 ),
 'ar' => array(
   'COUNTRY' => 'Argentina',
   'COUNTRY-CODE' => 'AR',
   'ISO-CODES' => 'ARG'
 ),
 'am' => array(
   'COUNTRY' => 'Armenia',
   'COUNTRY-CODE' => 'AM',
   'ISO-CODES' => 'ARM'
 ),
 'aw' => array(
   'COUNTRY' => 'Aruba',
   'COUNTRY-CODE' => 'AW',
   'ISO-CODES' => 'ABW'
 ),
 'au' => array(
   'COUNTRY' => 'Australia',
   'COUNTRY-CODE' => 'AU',
   'ISO-CODES' => 'AUS'
 ),
 'at' => array(
   'COUNTRY' => 'Austria',
   'COUNTRY-CODE' => 'AT',
   'ISO-CODES' => 'AUT'
 ),
 'az' => array(
   'COUNTRY' => 'Azerbaijan',
   'COUNTRY-CODE' => 'AZ',
   'ISO-CODES' => 'AZE'
 ),
 'bs' => array(
   'COUNTRY' => 'Bahamas',
   'COUNTRY-CODE' => 'BS',
   'ISO-CODES' => 'BHS'
 ),
 'bh' => array(
   'COUNTRY' => 'Bahrain',
   'COUNTRY-CODE' => 'BH',
   'ISO-CODES' => 'BHR'
 ),
 'bd' => array(
   'COUNTRY' => 'Bangladesh',
   'COUNTRY-CODE' => 'BD',
   'ISO-CODES' => 'BGD'
 ),
 'bb' => array(
   'COUNTRY' => 'Barbados',
   'COUNTRY-CODE' => 'BB',
   'ISO-CODES' => 'BRB'
 ),
 'by' => array(
   'COUNTRY' => 'Belarus',
   'COUNTRY-CODE' => 'BY',
   'ISO-CODES' => 'BLR'
 ),
 'be' => array(
   'COUNTRY' => 'Belgium',
   'COUNTRY-CODE' => 'BE',
   'ISO-CODES' => 'BEL'
 ),
 'bz' => array(
   'COUNTRY' => 'Belize',
   'COUNTRY-CODE' => 'BZ',
   'ISO-CODES' => 'BLZ'
 ),
 'bj' => array(
   'COUNTRY' => 'Benin',
   'COUNTRY-CODE' => 'BJ',
   'ISO-CODES' => 'BEN'
 ),
 'bm' => array(
   'COUNTRY' => 'Bermuda',
   'COUNTRY-CODE' => 'BM',
   'ISO-CODES' => 'BMU'
 ),
 'bt' => array(
   'COUNTRY' => 'Bhutan',
   'COUNTRY-CODE' => 'BT',
   'ISO-CODES' => 'BTN'
 ),
 'bo' => array(
   'COUNTRY' => 'Bolivia',
   'COUNTRY-CODE' => 'BO',
   'ISO-CODES' => 'BOL'
 ),
 'ba' => array(
   'COUNTRY' => 'Bosnia and Herzegovina',
   'COUNTRY-CODE' => 'BA',
   'ISO-CODES' => 'BIH'
 ),
 'bw' => array(
   'COUNTRY' => 'Botswana',
   'COUNTRY-CODE' => 'BW',
   'ISO-CODES' => 'BWA'
 ),
 'br' => array(
   'COUNTRY' => 'Brazil',
   'COUNTRY-CODE' => 'BR',
   'ISO-CODES' => 'BRA'
 ),
 'io' => array(
   'COUNTRY' => 'British Indian Ocean Territory',
   'COUNTRY-CODE' => 'IO',
   'ISO-CODES' => 'IOT'
 ),
 'vg' => array(
   'COUNTRY' => 'British Virgin Islands',
   'COUNTRY-CODE' => 'VG',
   'ISO-CODES' => 'VGB'
 ),
 'bn' => array(
   'COUNTRY' => 'Brunei',
   'COUNTRY-CODE' => 'BN',
   'ISO-CODES' => 'BRN'
 ),
 'bg' => array(
   'COUNTRY' => 'Bulgaria',
   'COUNTRY-CODE' => 'BG',
   'ISO-CODES' => 'BGR'
 ),
 'bf' => array(
   'COUNTRY' => 'Burkina Faso',
   'COUNTRY-CODE' => 'BF',
   'ISO-CODES' => 'BFA'
 ),
 'bi' => array(
   'COUNTRY' => 'Burundi',
   'COUNTRY-CODE' => 'BI',
   'ISO-CODES' => 'BDI'
 ),
 'kh' => array(
   'COUNTRY' => 'Cambodia',
   'COUNTRY-CODE' => 'KH',
   'ISO-CODES' => 'KHM'
 ),
 'cm' => array(
   'COUNTRY' => 'Cameroon',
   'COUNTRY-CODE' => 'CM',
   'ISO-CODES' => 'CMR'
 ),
 'ca' => array(
   'COUNTRY' => 'Canada',
   'COUNTRY-CODE' => 'CA',
   'ISO-CODES' => 'CAN'
 ),
 'cv' => array(
   'COUNTRY' => 'Cape Verde',
   'COUNTRY-CODE' => 'CV',
   'ISO-CODES' => 'CPV'
 ),
 'ky' => array(
   'COUNTRY' => 'Cayman Islands',
   'COUNTRY-CODE' => 'KY',
   'ISO-CODES' => 'CYM'
 ),
 'cf' => array(
   'COUNTRY' => 'Central African Republic',
   'COUNTRY-CODE' => 'CF',
   'ISO-CODES' => 'CAF'
 ),
 'td' => array(
   'COUNTRY' => 'Chad',
   'COUNTRY-CODE' => 'TD',
   'ISO-CODES' => 'TCD'
 ),
 'cl' => array(
   'COUNTRY' => 'Chile',
   'COUNTRY-CODE' => 'CL',
   'ISO-CODES' => 'CHL'
 ),
 'cn' => array(
   'COUNTRY' => 'China',
   'COUNTRY-CODE' => 'CN',
   'ISO-CODES' => 'CHN'
 'cx' => array(
   'COUNTRY' => 'Christmas Island',
   'COUNTRY-CODE' => 'CX',
   'ISO-CODES' => 'CXR'
 ),
 'cc' => array(
   'COUNTRY' => 'Cocos Islands',
   'COUNTRY-CODE' => 'CC',
   'ISO-CODES' => 'CCK'
 ),
 'co' => array(
   'COUNTRY' => 'Colombia',
   'COUNTRY-CODE' => 'CO',
   'ISO-CODES' => 'COL'
 ),
 'km' => array(
   'COUNTRY' => 'Comoros',
   'COUNTRY-CODE' => 'KM',
   'ISO-CODES' => 'COM'
 ),
 'ck' => array(
   'COUNTRY' => 'Cook Islands',
   'COUNTRY-CODE' => 'CK',
   'ISO-CODES' => 'COK'
 ),
 'cr' => array(
   'COUNTRY' => 'Costa Rica',
   'COUNTRY-CODE' => 'CR',
   'ISO-CODES' => 'CRI'
 ),
 'hr' => array(
   'COUNTRY' => 'Croatia',
   'COUNTRY-CODE' => 'HR',
   'ISO-CODES' => 'HRV'
 ),
 'cu' => array(
   'COUNTRY' => 'Cuba',
   'COUNTRY-CODE' => 'CU',
   'ISO-CODES' => 'CUB'
 ),
 'cw' => array(
   'COUNTRY' => 'Curacao',
   'COUNTRY-CODE' => 'CW',
   'ISO-CODES' => 'CUW'
 ),
 'cy' => array(
   'COUNTRY' => 'Cyprus',
   'COUNTRY-CODE' => 'CY',
   'ISO-CODES' => 'CYP'
 ),
 'cz' => array(
   'COUNTRY' => 'Czech Republic',
   'COUNTRY-CODE' => 'CZ',
   'ISO-CODES' => 'CZE'
 ),
 'cd' => array(
   'COUNTRY' => 'Democratic Republic of the Congo',
   'COUNTRY-CODE' => 'CD',
   'ISO-CODES' => 'COD'
 ),
 'dk' => array(
   'COUNTRY' => 'Denmark',
   'COUNTRY-CODE' => 'DK',
   'ISO-CODES' => 'DNK'
 ),
 'dj' => array(
   'COUNTRY' => 'Djibouti',
   'COUNTRY-CODE' => 'DJ',
   'ISO-CODES' => 'DJI'
 ),
 'dm' => array(
   'COUNTRY' => 'Dominica',
   'COUNTRY-CODE' => 'DM',
   'ISO-CODES' => 'DMA'
 ),
 'do' => array(
   'COUNTRY' => 'Dominican Republic',
   'COUNTRY-CODE' => 'DO',
   'ISO-CODES' => 'DOM'
 ),
 'tl' => array(
   'COUNTRY' => 'East Timor',
   'COUNTRY-CODE' => 'TL',
   'ISO-CODES' => 'TLS'
 ),
 'ec' => array(
   'COUNTRY' => 'Ecuador',
   'COUNTRY-CODE' => 'EC',
   'ISO-CODES' => 'ECU'
 ),
 'eg' => array(
   'COUNTRY' => 'Egypt',
   'COUNTRY-CODE' => 'EG',
   'ISO-CODES' => 'EGY'
 ),
 'sv' => array(
   'COUNTRY' => 'El Salvador',
   'COUNTRY-CODE' => 'SV',
   'ISO-CODES' => 'SLV'
 ),
 gq'' => array(
   'COUNTRY' => 'Equatorial Guinea',
   'COUNTRY-CODE' => 'GQ',
   'ISO-CODES' => 'GNQ'
 ),
 'er' => array(
   'COUNTRY' => 'Eritrea',
   'COUNTRY-CODE' => 'ER',
   'ISO-CODES' => 'ERI'
 ),
 'ee' => array(
   'COUNTRY' => 'Estonia',
   'COUNTRY-CODE' => 'EE',
   'ISO-CODES' => 'EST'
 ),
 'et' => array(
   'COUNTRY' => 'Ethiopia',
   'COUNTRY-CODE' => 'ET',
   'ISO-CODES' => 'ETH'
 ),
 'fk' => array(
   'COUNTRY' => 'Falkland Islands',
   'COUNTRY-CODE' => 'FK',
   'ISO-CODES' => 'FLK'
 ),
 'fo' => array(
   'COUNTRY' => 'Faroe Islands',
   'COUNTRY-CODE' => 'FO',
   'ISO-CODES' => 'FRO'
 ),
 'fj' => array(
   'COUNTRY' => 'Fiji',
   'COUNTRY-CODE' => 'FJ',
   'ISO-CODES' => 'FJI'
 ),
 'fi' => array(
   'COUNTRY' => 'Finland',
   'COUNTRY-CODE' => 'FI',
   'ISO-CODES' => 'FIN'
 ),
 'fr' => array(
   'COUNTRY' => 'France',
   'COUNTRY-CODE' => 'FR',
   'ISO-CODES' => 'FRA'
 ),
 'pf' => array(
   'COUNTRY' => 'French Polynesia',
   'COUNTRY-CODE' => 'PF',
   'ISO-CODES' => 'PYF'
 ),
 'ga' => array(
   'COUNTRY' => 'Gabon',
   'COUNTRY-CODE' => 'GA',
   'ISO-CODES' => 'GAB'
 ),
 'gm' => array(
   'COUNTRY' => 'Gambia',
   'COUNTRY-CODE' => 'GM',
   'ISO-CODES' => 'GMB'
 ),
 'ge' => array(
   'COUNTRY' => 'Georgia',
   'COUNTRY-CODE' => 'GE',
   'ISO-CODES' => 'GEO'
 ),
 'de' => array(
   'COUNTRY' => 'Germany',
   'COUNTRY-CODE' => 'DE',
   'ISO-CODES' => 'DEU'
 ),
 'gh' => array(
   'COUNTRY' => 'Ghana',
   'COUNTRY-CODE' => 'GH',
   'ISO-CODES' => 'GHA'
 ),
 'gi' => array(
   'COUNTRY' => 'Gibraltar',
   'COUNTRY-CODE' => 'GI',
   'ISO-CODES' => 'GIB'
 ),
 'gr' => array(
   'COUNTRY' => 'Greece',
   'COUNTRY-CODE' => 'GR',
   'ISO-CODES' => 'GRC'
 ),
 'gl' => array(
   'COUNTRY' => 'Greenland',
   'COUNTRY-CODE' => 'GL',
   'ISO-CODES' => 'GRL'
 ),
 'gd' => array(
   'COUNTRY' => 'Grenada',
   'COUNTRY-CODE' => 'GD',
   'ISO-CODES' => 'GRD'
 ),
 'gu' => array(
   'COUNTRY' => 'Guam',
   'COUNTRY-CODE' => 'GU',
   'ISO-CODES' => 'GUM'
 ),
 'gt' => array(
   'COUNTRY' => 'Guatemala',
   'COUNTRY-CODE' => 'GT',
   'ISO-CODES' => 'GTM'
 ),
 'gg' => array(
   'COUNTRY' => 'Guernsey',
   'COUNTRY-CODE' => 'GG',
   'ISO-CODES' => 'GGY'
 ),
 'gn' => array(
   'COUNTRY' => 'Guinea',
   'COUNTRY-CODE' => 'GN',
   'ISO-CODES' => 'GIN'
 ),
 'gw' => array(
   'COUNTRY' => 'Guinea-Bissau',
   'COUNTRY-CODE' => 'GW',
   'ISO-CODES' => 'GNB'
 ),
 'gy' => array(
   'COUNTRY' => 'Guyana',
   'COUNTRY-CODE' => 'GY',
   'ISO-CODES' => 'GUY'
 ),
 'ht' => array(
   'COUNTRY' => 'Haiti',
   'COUNTRY-CODE' => 'HT',
   'ISO-CODES' => 'HTI'
 ),
 'hn' => array(
   'COUNTRY' => 'Honduras',
   'COUNTRY-CODE' => 'HN',
   'ISO-CODES' => 'HND'
 ),
 'hk' => array(
   'COUNTRY' => 'Hong Kong',
   'COUNTRY-CODE' => 'HK',
   'ISO-CODES' => 'HKG'
 ),
 'hu' => array(
   'COUNTRY' => 'Hungary',
   'COUNTRY-CODE' => 'HU',
   'ISO-CODES' => 'HUN'
 ),
 'is' => array(
   'COUNTRY' => 'Iceland',
   'COUNTRY-CODE' => 'IS',
   'ISO-CODES' => 'ISL'
 ),
 'in' => array(
   'COUNTRY' => 'India',
   'COUNTRY-CODE' => 'IN',
   'ISO-CODES' => 'IND'
 ),
 'id' => array(
   'COUNTRY' => 'Indonesia',
   'COUNTRY-CODE' => 'ID',
   'ISO-CODES' => 'IDN'
 ),
 'ir' => array(
   'COUNTRY' => 'Iran',
   'COUNTRY-CODE' => 'IR',
   'ISO-CODES' => 'IRN'
 ),
 'iq' => array(
   'COUNTRY' => 'Iraq',
   'COUNTRY-CODE' => 'IQ',
   'ISO-CODES' => 'IRQ'
 ),
 'ie' => array(
   'COUNTRY' => 'Ireland',
   'COUNTRY-CODE' => 'IE',
   'ISO-CODES' => 'IRL'
 ),
 'im' => array(
   'COUNTRY' => 'Isle of Man',
   'COUNTRY-CODE' => 'IM',
   'ISO-CODES' => 'IMN'
 ),
 'il' => array(
   'COUNTRY' => 'Israel',
   'COUNTRY-CODE' => 'IL',
   'ISO-CODES' => 'ISR'
 ),
 'it' => array(
   'COUNTRY' => 'Italy',
   'COUNTRY-CODE' => 'IT',
   'ISO-CODES' => 'ITA'
 ),
 'ci' => array(
   'COUNTRY' => 'Ivory Coast',
   'COUNTRY-CODE' => 'CI',
   'ISO-CODES' => 'CIV'
 ),
 'jm' => array(
   'COUNTRY' => 'Jamaica',
   'COUNTRY-CODE' => 'JM',
   'ISO-CODES' => 'JAM'
 ),
 'jp' => array(
   'COUNTRY' => 'Japan',
   'COUNTRY-CODE' => 'JP',
   'ISO-CODES' => 'JPN'
 ),
 'je' => array(
   'COUNTRY' => 'Jersey',
   'COUNTRY-CODE' => 'JE',
   'ISO-CODES' => 'JEY'
 ),
 'jo' => array(
   'COUNTRY' => 'Jordan',
   'COUNTRY-CODE' => 'JO',
   'ISO-CODES' => 'JOR'
 ),
 'kz' => array(
   'COUNTRY' => 'Kazakhstan',
   'COUNTRY-CODE' => 'KZ',
   'ISO-CODES' => 'KAZ'
 ),
 'ke' => array(
   'COUNTRY' => 'Kenya',
   'COUNTRY-CODE' => 'KE',
   'ISO-CODES' => 'KEN'
 ),
 'ki' => array(
   'COUNTRY' => 'Kiribati',
   'COUNTRY-CODE' => 'KI',
   'ISO-CODES' => 'KIR'
 ),
 'xk' => array(
   'COUNTRY' => 'Kosovo',
   'COUNTRY-CODE' => 'XK',
   'ISO-CODES' => 'XKX'
 ),
 'kw' => array(
   'COUNTRY' => 'Kuwait',
   'COUNTRY-CODE' => 'KW',
   'ISO-CODES' => 'KWT'
 ),
 'kg' => array(
   'COUNTRY' => 'Kyrgyzstan',
   'COUNTRY-CODE' => 'KG',
   'ISO-CODES' => 'KGZ'
 ),
 'la' => array(
   'COUNTRY' => 'Laos',
   'COUNTRY-CODE' => 'LA',
   'ISO-CODES' => 'LAO'
 ),
 'lv' => array(
   'COUNTRY' => 'Latvia',
   'COUNTRY-CODE' => 'LV',
   'ISO-CODES' => 'LVA'
 ),
 'lb' => array(
   'COUNTRY' => 'Lebanon',
   'COUNTRY-CODE' => 'LB',
   'ISO-CODES' => 'LBN'
 ),
 'ls' => array(
   'COUNTRY' => 'Lesotho',
   'COUNTRY-CODE' => 'LS',
   'ISO-CODES' => 'LSO'
 ),
 'lr' => array(
   'COUNTRY' => 'Liberia',
   'COUNTRY-CODE' => 'LR',
   'ISO-CODES' => 'LBR'
 ),
 'ly' => array(
   'COUNTRY' => 'Libya',
   'COUNTRY-CODE' => 'LY',
   'ISO-CODES' => 'LBY'
 ),
 'li' => array(
   'COUNTRY' => 'Liechtenstein',
   'COUNTRY-CODE' => 'LI',
   'ISO-CODES' => 'LIE'
 ),
 'lt' => array(
   'COUNTRY' => 'Lithuania',
   'COUNTRY-CODE' => 'LT',
   'ISO-CODES' => 'LTU'
 ),
 'lu' => array(
   'COUNTRY' => 'Luxembourg',
   'COUNTRY-CODE' => 'LU',
   'ISO-CODES' => 'LUX'
 ),
 'mo' => array(
   'COUNTRY' => 'Macau',
   'COUNTRY-CODE' => 'MO',
   'ISO-CODES' => 'MAC'
 ),
 'mk' => array(
   'COUNTRY' => 'Macedonia',
   'COUNTRY-CODE' => 'MK',
   'ISO-CODES' => 'MKD'
 ),
 'mg' => array(
   'COUNTRY' => 'Madagascar',
   'COUNTRY-CODE' => 'MG',
   'ISO-CODES' => 'MDG'
 ),
 'mw' => array(
   'COUNTRY' => 'Malawi',
   'COUNTRY-CODE' => 'MW',
   'ISO-CODES' => 'MWI'
 ),
 'my' => array(
   'COUNTRY' => 'Malaysia',
   'COUNTRY-CODE' => 'MY',
   'ISO-CODES' => 'MYS'
 ),
 'mv' => array(
   'COUNTRY' => 'Maldives',
   'COUNTRY-CODE' => 'MV',
   'ISO-CODES' => 'MDV'
 ),
 'ml' => array(
   'COUNTRY' => 'Mali',
   'COUNTRY-CODE' => 'ML',
   'ISO-CODES' => 'MLI'
 ),
 'mt' => array(
   'COUNTRY' => 'Malta',
   'COUNTRY-CODE' => 'MT',
   'ISO-CODES' => 'MLT'
 ),
 'mh' => array(
   'COUNTRY' => 'Marshall Islands',
   'COUNTRY-CODE' => 'MH',
   'ISO-CODES' => 'MHL'
 ),
 'mr' => array(
   'COUNTRY' => 'Mauritania',
   'COUNTRY-CODE' => 'MR',
   'ISO-CODES' => 'MRT'
 ),
 'mu' => array(
   'COUNTRY' => 'Mauritius',
   'COUNTRY-CODE' => 'MU',
   'ISO-CODES' => 'MUS'
 ),
 'yt' => array(
   'COUNTRY' => 'Mayotte',
   'COUNTRY-CODE' => 'YT',
   'ISO-CODES' => 'MYT'
 ),
 'mx' => array(
   'COUNTRY' => 'Mexico',
   'COUNTRY-CODE' => 'MX',
   'ISO-CODES' => 'MEX'
 ),
 'fm' => array(
   'COUNTRY' => 'Micronesia',
   'COUNTRY-CODE' => 'FM',
   'ISO-CODES' => 'FSM'
 ),
 'md' => array(
   'COUNTRY' => 'Moldova',
   'COUNTRY-CODE' => 'MD',
   'ISO-CODES' => 'MDA'
 ),
 'mc' => array(
   'COUNTRY' => 'Monaco',
   'COUNTRY-CODE' => 'MC',
   'ISO-CODES' => 'MCO'
 ),
 'mn' => array(
   'COUNTRY' => 'Mongolia',
   'COUNTRY-CODE' => 'MN',
   'ISO-CODES' => 'MNG'
 ),
 'me' => array(
   'COUNTRY' => 'Montenegro',
   'COUNTRY-CODE' => 'ME',
   'ISO-CODES' => 'MNE'
 ),
 'ms' => array(
   'COUNTRY' => 'Montserrat',
   'COUNTRY-CODE' => 'MS',
   'ISO-CODES' => 'MSR'
 ),
 'ma' => array(
   'COUNTRY' => 'Morocco',
   'COUNTRY-CODE' => 'MA',
   'ISO-CODES' => 'MAR'
 ),
 'nz' => array(
   'COUNTRY' => 'Mozambique',
   'COUNTRY-CODE' => 'MZ',
   'ISO-CODES' => 'MOZ'
 ),
 'mm' => array(
   'COUNTRY' => 'Myanmar',
   'COUNTRY-CODE' => 'MM',
   'ISO-CODES' => 'MMR'
 ),
 'na' => array(
   'COUNTRY' => 'Namibia',
   'COUNTRY-CODE' => 'NA',
   'ISO-CODES' => 'NAM'
 ),
 'nr' => array(
   'COUNTRY' => 'Nauru',
   'COUNTRY-CODE' => 'NR',
   'ISO-CODES' => 'NRU'
 ),
 'np' => array(
   'COUNTRY' => 'Nepal',
   'COUNTRY-CODE' => 'NP',
   'ISO-CODES' => 'NPL'
 ),
 'nl' => array(
   'COUNTRY' => 'Netherlands',
   'COUNTRY-CODE' => 'NL',
   'ISO-CODES' => 'NLD'
 ),
 'an' => array(
   'COUNTRY' => 'Netherlands Antilles',
   'COUNTRY-CODE' => 'AN',
   'ISO-CODES' => 'ANT'
 ),
 'nz' => array(
   'COUNTRY' => 'New Caledonia',
   'COUNTRY-CODE' => 'NC',
   'ISO-CODES' => 'NCL'
 ),
 'nz' => array(
   'COUNTRY' => 'New Zealand',
   'COUNTRY-CODE' => 'NZ',
   'ISO-CODES' => 'NZL'
 ),
 'ni' => array(
   'COUNTRY' => 'Nicaragua',
   'COUNTRY-CODE' => 'NI',
   'ISO-CODES' => 'NIC'
 ),
 'ne' => array(
   'COUNTRY' => 'Niger',
   'COUNTRY-CODE' => 'NE',
   'ISO-CODES' => 'NER'
 ),
 'ng' => array(
   'COUNTRY' => 'Nigeria',
   'COUNTRY-CODE' => 'NG',
   'ISO-CODES' => 'NGA'
 ),
 'nu' => array(
   'COUNTRY' => 'Niue',
   'COUNTRY-CODE' => 'NU',
   'ISO-CODES' => 'NIU'
 ),
 'kp' => array(
   'COUNTRY' => 'North Korea',
   'COUNTRY-CODE' => 'KP',
   'ISO-CODES' => 'PRK'
 ),
 'mp' => array(
   'COUNTRY' => 'Northern Mariana Islands',
   'COUNTRY-CODE' => 'MP',
   'ISO-CODES' => 'MNP'
 ),
 'no' => array(
   'COUNTRY' => 'Norway',
   'COUNTRY-CODE' => 'NO',
   'ISO-CODES' => 'NOR'
 ),
 'om' => array(
   'COUNTRY' => 'Oman',
   'COUNTRY-CODE' => 'OM',
   'ISO-CODES' => 'OMN'
 ),
 'ph' => array(
   'COUNTRY' => 'Pakistan',
   'COUNTRY-CODE' => 'PK',
   'ISO-CODES' => 'PAK'
 ),
 'pw' => array(
   'COUNTRY' => 'Palau',
   'COUNTRY-CODE' => 'PW',
   'ISO-CODES' => 'PLW'
 ),
 'ps' => array(
   'COUNTRY' => 'Palestine',
   'COUNTRY-CODE' => 'PS',
   'ISO-CODES' => 'PSE'
 ),
 'pa' => array(
   'COUNTRY' => 'Panama',
   'COUNTRY-CODE' => 'PA',
   'ISO-CODES' => 'PAN'
 ),
 'pg' => array(
   'COUNTRY' => 'Papua New Guinea',
   'COUNTRY-CODE' => 'PG',
   'ISO-CODES' => 'PNG'
 ),
 'py' => array(
   'COUNTRY' => 'Paraguay',
   'COUNTRY-CODE' => 'PY',
   'ISO-CODES' => 'PRY'
 ),
 'pe' => array(
   'COUNTRY' => 'Peru',
   'COUNTRY-CODE' => 'PE',
   'ISO-CODES' => 'PER'
 ),
 'ph' => array(
   'COUNTRY' => 'Philippines',
   'COUNTRY-CODE' => 'PH',
   'ISO-CODES' => 'PHL'
 ),
 'pn' => array(
   'COUNTRY' => 'Pitcairn',
   'COUNTRY-CODE' => 'PN',
   'ISO-CODES' => 'PCN'
 ),
 'pl' => array(
   'COUNTRY' => 'Poland',
   'COUNTRY-CODE' => 'PL',
   'ISO-CODES' => 'POL'
   'GDP $USD' => ''
 ),
 'pt' => array(
   'COUNTRY' => 'Portugal',
   'COUNTRY-CODE' => 'PT',
   'ISO-CODES' => 'PRT'
 ),
 'pr' => array(
   'COUNTRY' => 'Puerto Rico',
   'COUNTRY-CODE' => 'PR',
   'ISO-CODES' => 'PRI'
 ),
 'qa' => array(
   'COUNTRY' => 'Qatar',
   'COUNTRY-CODE' => 'QA',
   'ISO-CODES' => 'QAT'
 ),
 'cg' => array(
   'COUNTRY' => 'Republic of the Congo',
   'COUNTRY-CODE' => 'CG',
   'ISO-CODES' => 'COG'
 ),
 're' => array(
   'COUNTRY' => 'Reunion',
   'COUNTRY-CODE' => 'RE',
   'ISO-CODES' => 'REU'
 ),
 'ro' => array(
   'COUNTRY' => 'Romania',
   'COUNTRY-CODE' => 'RO',
   'ISO-CODES' => 'ROU'
 ),
 'ru' => array(
   'COUNTRY' => 'Russia',
   'COUNTRY-CODE' => 'RU',
   'ISO-CODES' => 'RUS'
 ),
 'rw' => array(
   'COUNTRY' => 'Rwanda',
   'COUNTRY-CODE' => 'RW',
   'ISO-CODES' => 'RWA'
 ),
 'bl' => array(
   'COUNTRY' => 'Saint Barthelemy',
   'COUNTRY-CODE' => 'BL',
   'ISO-CODES' => 'BLM'
 ),
 'sh' => array(
   'COUNTRY' => 'Saint Helena',
   'COUNTRY-CODE' => 'SH',
   'ISO-CODES' => 'SHN'
 ),
 'kn' => array(
   'COUNTRY' => 'Saint Kitts and Nevis',
   'COUNTRY-CODE' => 'KN',
   'ISO-CODES' => 'KNA'
 ),
 'lc' => array(
   'COUNTRY' => 'Saint Lucia',
   'COUNTRY-CODE' => 'LC',
   'ISO-CODES' => 'LCA'
 ),
 'mf' => array(
   'COUNTRY' => 'Saint Martin',
   'COUNTRY-CODE' => 'MF',
   'ISO-CODES' => 'MAF'
 ),
 'pm' => array(
   'COUNTRY' => 'Saint Pierre and Miquelon',
   'COUNTRY-CODE' => 'PM',
   'ISO-CODES' => 'SPM'
 ),
 'vc' => array(
   'COUNTRY' => 'Saint Vincent and the Grenadines',
   'COUNTRY-CODE' => 'VC',
   'ISO-CODES' => 'VCT'
 ),
 'ws' => array(
   'COUNTRY' => 'Samoa',
   'COUNTRY-CODE' => 'WS',
   'ISO-CODES' => 'WSM'
 ),
 'sm' => array(
   'COUNTRY' => 'San Marino',
   'COUNTRY-CODE' => 'SM',
   'ISO-CODES' => 'SMR'
 ),
 'st' => array(
   'COUNTRY' => 'Sao Tome and Principe',
   'COUNTRY-CODE' => 'ST',
   'ISO-CODES' => 'STP'
 ),
 'sa' => array(
   'COUNTRY' => 'Saudi Arabia',
   'COUNTRY-CODE' => 'SA',
   'ISO-CODES' => 'SAU'
 ),
 'sn' => array(
   'COUNTRY' => 'Senegal',
   'COUNTRY-CODE' => 'SN',
   'ISO-CODES' => 'SEN'
 ),
 'rs' => array(
   'COUNTRY' => 'Serbia',
   'COUNTRY-CODE' => 'RS',
   'ISO-CODES' => 'SRB'
 ),
 'sc' => array(
   'COUNTRY' => 'Seychelles',
   'COUNTRY-CODE' => 'SC',
   'ISO-CODES' => 'SYC'
 ),
 'sl' => array(
   'COUNTRY' => 'Sierra Leone',
   'COUNTRY-CODE' => 'SL',
   'ISO-CODES' => 'SLE'
 ),
 'sg' => array(
   'COUNTRY' => 'Singapore',
   'COUNTRY-CODE' => 'SG',
   'ISO-CODES' => 'SGP'
 ),
 'sx' => array(
   'COUNTRY' => 'Sint Maarten',
   'COUNTRY-CODE' => 'SX',
   'ISO-CODES' => 'SXM'
 ),
 'sk' => array(
   'COUNTRY' => 'Slovakia',
   'COUNTRY-CODE' => 'SK',
   'ISO-CODES' => 'SVK'
 ),
 'si' => array(
   'COUNTRY' => 'Slovenia',
   'COUNTRY-CODE' => 'SI',
   'ISO-CODES' => 'SVN'
 ),
 'sb' => array(
   'COUNTRY' => 'Solomon Islands',
   'COUNTRY-CODE' => 'SB',
   'ISO-CODES' => 'SLB'
 ),
 'sq' => array(
   'COUNTRY' => 'Somalia',
   'COUNTRY-CODE' => 'SO',
   'ISO-CODES' => 'SOM'
 ),
 'za' => array(
   'COUNTRY' => 'South Africa',
   'COUNTRY-CODE' => 'ZA',
   'ISO-CODES' => 'ZAF'
 ),
 'kr' => array(
   'COUNTRY' => 'South Korea',
   'COUNTRY-CODE' => 'KR',
   'ISO-CODES' => 'KOR'
 ),
 'ss' => array(
   'COUNTRY' => 'South Sudan',
   'COUNTRY-CODE' => 'SS',
   'ISO-CODES' => 'SSD'
 ),
 'es' => array(
   'COUNTRY' => 'Spain',
   'COUNTRY-CODE' => 'ES',
   'ISO-CODES' => 'ESP'
 ),
 'lk' => array(
   'COUNTRY' => 'Sri Lanka',
   'COUNTRY-CODE' => 'LK',
   'ISO-CODES' => 'LKA'
 ),
 'sd' => array(
   'COUNTRY' => 'Sudan',
   'COUNTRY-CODE' => 'SD',
   'ISO-CODES' => 'SDN'
 ),
 'sr' => array(
   'COUNTRY' => 'Suriname',
   'COUNTRY-CODE' => 'SR',
   'ISO-CODES' => 'SUR'
 ),
 'sj' => array(
   'COUNTRY' => 'Svalbard and Jan Mayen',
   'COUNTRY-CODE' => 'SJ',
   'ISO-CODES' => 'SJM'
 ),
 'sz' => array(
   'COUNTRY' => 'Swaziland',
   'COUNTRY-CODE' => 'SZ',
   'ISO-CODES' => 'SWZ'
 ),
 'se' => array(
   'COUNTRY' => 'Sweden',
   'COUNTRY-CODE' => 'SE',
   'ISO-CODES' => 'SWE'
 ),
 'ch' => array(
   'COUNTRY' => 'Switzerland',
   'COUNTRY-CODE' => 'CH',
   'ISO-CODES' => 'CHE'
 ),
 'sy' => array(
   'COUNTRY' => 'Syria',
   'COUNTRY-CODE' => 'SY',
   'ISO-CODES' => 'SYR'
 ),
 'tw' => array(
   'COUNTRY' => 'Taiwan',
   'COUNTRY-CODE' => 'TW',
   'ISO-CODES' => 'TWN'
 ),
 'tj' => array(
   'COUNTRY' => 'Tajikistan',
   'COUNTRY-CODE' => 'TJ',
   'ISO-CODES' => 'TJK'
 ),
 'tz' => array(
   'COUNTRY' => 'Tanzania',
   'COUNTRY-CODE' => 'TZ',
   'ISO-CODES' => 'TZA'
 ),
 'th' => array(
   'COUNTRY' => 'Thailand',
   'COUNTRY-CODE' => 'TH',
   'ISO-CODES' => 'THA'
 ),
 'tg' => array(
   'COUNTRY' => 'Togo',
   'COUNTRY-CODE' => 'TG',
   'ISO-CODES' => 'TGO'
 ),
 'tk' => array(
   'COUNTRY' => 'Tokelau',
   'COUNTRY-CODE' => 'TK',
   'ISO-CODES' => 'TKL'
 ),
 'to' => array(
   'COUNTRY' => 'Tonga',
   'COUNTRY-CODE' => 'TO',
   'ISO-CODES' => 'TON'
 ),
 'tt' => array(
   'COUNTRY' => 'Trinidad and Tobago',
   'COUNTRY-CODE' => 'TT',
   'ISO-CODES' => 'TTO'
 ),
 'tn' => array(
   'COUNTRY' => 'Tunisia',
   'COUNTRY-CODE' => 'TN',
   'ISO-CODES' => 'TUN'
 ),
 'tr' => array(
   'COUNTRY' => 'Turkey',
   'COUNTRY-CODE' => 'TR',
   'ISO-CODES' => 'TUR'
 ),
 'tm' => array(
   'COUNTRY' => 'Turkmenistan',
   'COUNTRY-CODE' => 'TM',
   'ISO-CODES' => 'TKM'
 ),
 'tc' => array(
   'COUNTRY' => 'Turks and Caicos Islands',
   'COUNTRY-CODE' => 'TC',
   'ISO-CODES' => 'TCA'
 ),
 'tv' => array(
   'COUNTRY' => 'Tuvalu',
   'COUNTRY-CODE' => 'TV',
   'ISO-CODES' => 'TUV'
 ),
 'vi' => array(
   'COUNTRY' => 'U.S. Virgin Islands',
   'COUNTRY-CODE' => 'VI',
   'ISO-CODES' => 'VIR'
 ),
 'ug' => array(
   'COUNTRY' => 'Uganda',
   'COUNTRY-CODE' => 'UG',
   'ISO-CODES' => 'UGA'
 ),
 'ua' => array(
   'COUNTRY' => 'Ukraine',
   'COUNTRY-CODE' => 'UA',
   'ISO-CODES' => 'UKR'
 ),
 'ae' => array(
   'COUNTRY' => 'United Arab Emirates',
   'COUNTRY-CODE' => 'AE',
   'ISO-CODES' => 'ARE'
 ),
 'gb' => array(
   'COUNTRY' => 'United Kingdom',
   'COUNTRY-CODE' => 'GB',
   'ISO-CODES' => 'GBR'
 ),
 'us' => array(
   'COUNTRY' => 'United States',
   'COUNTRY-CODE' => 'US',
   'ISO-CODES' => 'USA'
 ),
 'uy' => array(
   'COUNTRY' => 'Uruguay',
   'COUNTRY-CODE' => 'UY',
   'ISO-CODES' => 'URY'
 ),
 'uz' => array(
   'COUNTRY' => 'Uzbekistan',
   'COUNTRY-CODE' => 'UZ',
   'ISO-CODES' => 'UZB'
 ),
 'vu' => array(
   'COUNTRY' => 'Vanuatu',
   'COUNTRY-CODE' => 'VU',
   'ISO-CODES' => 'VUT'
 ),
 'va' => array(
   'COUNTRY' => 'Vatican',
   'COUNTRY-CODE' => 'VA',
   'ISO-CODES' => 'VAT'
 ),
 've' => array(
   'COUNTRY' => 'Venezuela',
   'COUNTRY-CODE' => 'VE',
   'ISO-CODES' => 'VEN'
 ),
 'vn' => array(
   'COUNTRY' => 'Vietnam',
   'COUNTRY-CODE' => 'VN',
   'ISO-CODES' => 'VNM'
 ),
 'wf' => array(
   'COUNTRY' => 'Wallis and Futuna',
   'COUNTRY-CODE' => 'WF',
   'ISO-CODES' => 'WLF'
 ),
 'eh' => array(
   'COUNTRY' => 'Western Sahara',
   'COUNTRY-CODE' => 'EH',
   'ISO-CODES' => 'ESH'
 ),
 'ye' => array(
   'COUNTRY' => 'Yemen',
   'COUNTRY-CODE' => 'YE',
   'ISO-CODES' => 'YEM'
 ),
 'zm' => array(
   'COUNTRY' => 'Zambia',
   'COUNTRY-CODE' => 'ZM',
   'ISO-CODES' => 'ZMB'
 ),
 'zw' => array(
   'COUNTRY' => 'Zimbabwe',
   'COUNTRY-CODE' => 'ZW',
   'ISO-CODES' => 'ZWE'
 )
);


$JE_PhoneRegionCodeManualNumbers = json_encode($PhoneRegionCodeManualNumbers);

?>