<?php header('Content-type: application/xml; charset=utf-8'); ?>
<?php echo '<rss version="2.0">
	<channel>
		<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/</link>
		<description>'.$website['home']['description'].'</description>
		<title>'.$website['info']['site']['name'].'</title>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['home']['url'].'</link>
			<description>'.$website['home']['description'].'</description>
			<title>'.$website['home']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['plombier']['url'].'</link>
			<description>'.$website['plombier']['description'].'</description>
			<title>'.$website['plombier']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['chauffagiste']['url'].'</link>
			<description>'.$website['chauffagiste']['description'].'</description>
			<title>'.$website['chauffagiste']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['vitrier']['url'].'</link>
			<description>'.$website['vitrier']['description'].'</description>
			<title>'.$website['vitrier']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['electricien']['url'].'</link>
			<description>'.$website['electricien']['description'].'</description>
			<title>'.$website['electricien']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['serrurier']['url'].'</link>
			<description>'.$website['serrurier']['description'].'</description>
			<title>'.$website['serrurier']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['volet-roulant-et-store']['url'].'</link>
			<description>'.$website['volet-roulant-et-store']['description'].'</description>
			<title>'.$website['volet-roulant-et-store']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['demande-devis']['url'].'</link>
			<description>'.$website['demande-devis']['description'].'</description>
			<title>'.$website['demande-devis']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['contactez-nous']['url'].'</link>
			<description>'.$website['contactez-nous']['description'].'</description>
			<title>'.$website['contactez-nous']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$website['plan-du-site']['url'].'</link>
			<description>'.$website['plan-du-site']['description'].'</description>
			<title>'.$website['plan-du-site']['title'].'</title>
		</item>
	</channel>
</rss>'; ?>